Repository hanami/model, pull requests merged in 2019-05, with the labels that each got.

#532 Remove global state
  .circleci/config.yml
  hanami-model.gemspec
  lib/hanami/model.rb
  lib/hanami/model/configuration.rb
  lib/hanami/model/migrator/mysql_adapter.rb
  lib/hanami/model/repository_configurer.rb
  lib/hanami/repository.rb
  spec/integration/hanami/model/associations/belongs_to_spec.rb
  spec/integration/hanami/model/associations/has_many_spec.rb
  spec/integration/hanami/model/associations/has_one_spec.rb
  spec/integration/hanami/model/associations/many_to_many_spec.rb
  spec/integration/hanami/model/associations/relation_alias_spec.rb
  spec/integration/hanami/model/repository/base_spec.rb
  spec/integration/hanami/model/repository/command_spec.rb
  spec/integration/hanami/model/repository/legacy_spec.rb
  spec/support/database.rb
  spec/support/database/strategies/abstract.rb
  spec/support/database/strategies/sql.rb
  spec/support/fixtures.rb
  spec/unit/hanami/model/load_spec.rb
  spec/unit/hanami/model/mapped_relation_spec.rb
Labels: breaking-change

#533 Updates the README with requiring sql documentation
  README.md
Labels: enhancement

#523 sqlite: handle optional quoting of identifiers
  lib/hanami/model/migrator/sqlite_adapter.rb
  spec/unit/hanami/model/migrator/sqlite.rb
Labels: fix

#509 Revert unintended change to has_many
  lib/hanami/model/associations/has_many.rb
  lib/hanami/repository.rb
Labels: fix
